#!/usr/bin/perl

open(FIND, "find . -print |") || die "Nao pode rodar ACHA: $!\n";

FILE:
while ($filename = <FIND>) {
  chop $filename;
  next FILE unless -T $filename;
  if (!open(TEXTFILE, $filename)) {
    print STDERR "Nao pode abrir $filename -- continuando ...\n";
    next FILE;
  }
  while (<TEXTFILE>) {
    foreach $word (@ARGV) {
      if (index($_, $word) >= 0) {
        print $filename, "\n";
        next FILE;
      }
    }
  }
}
